stack_name: "{{ var.environment }}-dataplatform-ingestion-workflow"
template_path: tp4/ingestion.yaml
parameters:
  Environment: {{ var.environment }}
  BucketPrefix: "{{ var.trainee }}-source"
  KMSKeyArn: !stack_output_external {{ var.environment }}-dataplatform-kms::KMSKeyArn
  IngestionWorkflowRegistry: !stack_output_external {{ var.environment }}-dataplatform-ecr::IngestionWorkflowRegistry
  Version: "{{ var.Version }}"
  EventbusName: "{{ var.trainee }}"