AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
  BucketName:
    Type: String

Outputs:
  BucketName:
    Value: !Ref Bucket
  BucketArn:
    Value: !GetAtt Bucket.Arn

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${BucketName}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      Tags:
        - Key: Environment
          Value: !Ref Environment

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Sid: Deny non SSL connection
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}"
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
