---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Ingestion pipeline data-platform'

Parameters:
  Environment:
    Type: String
    Description: Environment

  ArtifactBucketName:
    Type: String
    Description: "Name of artifact bucket"

  KMSKeyArn:
    Type: String

  BucketPrefix:
    Type: String
    Description: "Prefix of data buckets"

Resources:

  GlueCsvToParquetJob:
    Type: "AWS::Glue::Job"
    Properties:
      # TODO

  AWSGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        # TODO
      ManagedPolicyArns:
        # TODO
      Policies:
        # TODO
      Path: "/"