stack_name: "{{ var.environment }}-dataplatform-s3-{{ var.Source }}"
template_path: demo-share/s3.yaml
parameters:
  Environment: {{ var.environment }}
  BucketPrefix: "{{ var.trainee }}-source"
  Source: "{{ var.Source }}"
  KMSKeyArn: !stack_output_external {{ var.environment }}-dataplatform-kms::KMSKeyArn
  BucketNotificationUpdaterLambda: !stack_output_external {{ var.environment }}-dataplatform-s3-notification-updater::BucketNotificationUpdaterLambda
  LambdaLaunchIngestionWorkflowArn: !stack_output_external {{ var.environment }}-dataplatform-ingestion-workflow::LambdaLaunchStepFunctionsArn

  "OtherAccountId": "{{ var.other_account_id }}"