---
AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  IngestionWorkflowRegistry:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${IngestionWorkflow}"

Resources:
  IngestionWorkflow:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ingestion-workflow
